# Generated by Django 6.0 on 2025-12-22 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_candidate_photo_url'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='voter',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election')},
        ),
    ]
