# Generated by Django 6.0 on 2025-12-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_candidate_options_alter_election_options_and_more'),
        ('voting', '0002_rename_voter_id_vote_id_rename_user_id_vote_voter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='vote',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Vote verification hash from blockchain', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='blockchain_tx',
            field=models.CharField(blank=True, help_text='Transaction hash on blockchain', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
