# Generated by Django 6.0 on 2025-12-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='abi_interface',
            field=models.JSONField(blank=True, help_text='smart contract ABI for web 3 Interaction', null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
