# Generated by Django 6.0 on 2025-12-20 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_abi_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
