# Generated by Django 6.0 on 2025-12-21 18:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0003_alter_election_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("party", models.CharField(max_length=255)),
                ("photo_url", models.CharField(max_length=255)),
                (
                    "blockchain_id",
                    models.IntegerField(
                        blank=True, help_text="ID used in solidity", null=True
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="elections.election",
                    ),
                ),
            ],
        ),
    ]
