# Generated by Django 6.0 on 2025-12-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0006_alter_candidate_options_alter_election_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("name", "election"), name="unique_candidate_per_election"
            ),
        ),
    ]
