from uuid import uuid4

from django.conf import settings
from django.db import models
from elections.models import Candidate, Election


class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    voter = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="votes"
    )
    election = models.ForeignKey(
        Election, on_delete=models.CASCADE, related_name="votes"
    )
    candidate = models.ForeignKey(
        Candidate, on_delete=models.CASCADE, related_name="votes"
    )
    # Local vote hash (generated by Django)
    vote_hash = models.CharField(max_length=64, blank=True, null=True)
    # Blockchain fields - these connects to the smart contract
    blockchain_hash = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="Vote verification hash from blockchain",
    )
    blockchain_tx = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Transaction hash on blockchain",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        Metadata 0ptions for the Vote model
        """

        # This constraint ensures that a user can vote only once per election.
        unique_together = ("voter", "election")
        ordering = ["-created_at"]

    def __str__(self):
        """
        Returns a string representation of the Vote instance, useful for the Django Admin.
        """
        return f"{self.voter} -> {self.candidate} in {self.election}"
