# Generated by Django 6.0 on 2025-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_is_admin_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id_hash",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
